export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';


// Events
export const SEND_USER_EVENTS = 'SEND_USER_EVENTS';
export const SELECT_EVENT = 'SELECT_EVENT';
export const FETCHING_EVENT_DATA_START = 'FETCHING_EVENT_DATA_START';
export const FETCHING_EVENT_DATA_SUCCESS = 'FETCHING_EVENT_DATA_SUCCESS';
export const FETCHING_EVENT_DATA_FAIL = 'FETCHING_EVENT_DATA_FAIL';